### PR TITLE
Fix for not setting the correct position after changing type

### LINKED ISSUE #25: Overwrite position when changing type
Child of https://github.com/frontity/ads-form/issues/14

The default position is 0, it should be the first one of the first type.

After that, if the user changes the type, the position should be overwritten with the first value of that type:

because if we don't do that, position only changes when the user changes its value and we could be sending wrong positions.

### PR DESCRIPTION
**Pull request by luisherranz**
Fixes #25

### CODE REVIEW

File: components/AdForm/types.js [hunk 1]
```diff
@@ -1,27 +1,48 @@
...
 
-export const listPositions = ['before post 1'].concat(
-  range(1, 30).map(n => `after post ${n}`),
-);
+const MIN_LIMIT_VALUE = 300; // This must be equal to this: https://github.com/frontity/saturn-theme/blob/dev/src/shared/components/HtmlToReactConverter/injectSlots.js#L6
 
-export const singlePositions = ['before paragraph 1'].concat(
-  range(1, 30).map(n => `after paragraph ${n}`),
-);
+export const positions = {
```
Comment (orballo) [inline components/AdForm/types.js]: @luisherranz this file was already changed in the previous pull request, I don't know if this might provoke any conflicts.

Comment (luisherranz) [reply components/AdForm/types.js]: "This branch has no conflicts with the base branch" <- not in theory

Comment (luisherranz) [reply components/AdForm/types.js]: Oh, I just remembered I rebased this branch onto the other to avoid precisely that.
